import { 
  collection, doc, getDocs, setDoc, addDoc, updateDoc, deleteDoc, onSnapshot, query, orderBy, limit 
} from 'firebase/firestore';
import { db } from '../lib/firebase';
import { 
  Client, Motorcycle, Reservation, Revenue, Expense, MaintenanceRecord, Investment, 
  Tour, TourParticipant, EquipmentItem, Agency, Supplier, NotificationItem, AuditLogItem, BusinessSettings 
} from '../types';

// Storage keys for offline or quick fallback persistence
const DEMO_INIT_KEY = 'motonomad_demo_initialized_v2';

// Sample Demo Data Generator
export const sampleMotorcycles: Motorcycle[] = [
  {
    id: 'moto-1',
    brand: 'BMW',
    model: 'R 1250 GS Adventure',
    version: 'Triple Black Edition',
    year: 2024,
    registrationNumber: '67890-A-26',
    vin: 'WB10J9108P6R12001',
    color: 'Triple Black',
    category: 'Adventure',
    engineSize: 1254,
    purchaseDate: '2024-01-15',
    purchasePrice: 220000, // MAD
    residualValue: 120000,
    usefulLifeYears: 5,
    depreciationMethod: 'Straight-line',
    currentMileage: 14200,
    currentStatus: 'Rented',
    currentLocation: 'Marrakech HQ',
    supplier: 'SMEIA BMW Morocco',
    insuranceCompany: 'AXA Assurance Maroc',
    insurancePolicyNumber: 'POL-BMW-88912',
    insuranceExpiry: '2026-12-31',
    techInspectionExpiry: '2026-11-15',
    dailyPrice: 1400, // MAD
    weeklyPrice: 8400,
    monthlyPrice: 28000,
    depositAmount: 15000,
    photos: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 89600,
    totalMaintenanceCost: 12400,
    currentBookValue: 170000,
    estimatedMarketValue: 195000,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'moto-2',
    brand: 'Yamaha',
    model: 'Ténéré 700',
    version: 'Rally Edition',
    year: 2024,
    registrationNumber: '45123-B-26',
    vin: 'JYADM081000023412',
    color: 'Heritage Blue',
    category: 'Adventure',
    engineSize: 689,
    purchaseDate: '2024-02-10',
    purchasePrice: 135000,
    residualValue: 70000,
    usefulLifeYears: 5,
    depreciationMethod: 'Straight-line',
    currentMileage: 18500,
    currentStatus: 'Available',
    currentLocation: 'Marrakech HQ',
    supplier: 'Yamaha Morocco',
    insuranceCompany: 'Wafa Assurance',
    insurancePolicyNumber: 'POL-YAM-33412',
    insuranceExpiry: '2027-02-10',
    techInspectionExpiry: '2027-01-10',
    dailyPrice: 950,
    weeklyPrice: 5700,
    monthlyPrice: 19000,
    depositAmount: 10000,
    photos: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 64500,
    totalMaintenanceCost: 8200,
    currentBookValue: 102500,
    estimatedMarketValue: 118000,
    createdAt: '2024-02-10T10:00:00Z',
  },
  {
    id: 'moto-3',
    brand: 'Suzuki',
    model: 'V-Strom 800 DE',
    version: 'Explorer Pack',
    year: 2024,
    registrationNumber: '11223-D-26',
    vin: 'JS1EF111000019283',
    color: 'Champion Yellow',
    category: 'Adventure',
    engineSize: 776,
    purchaseDate: '2024-03-01',
    purchasePrice: 125000,
    residualValue: 60000,
    usefulLifeYears: 5,
    depreciationMethod: 'Straight-line',
    currentMileage: 11200,
    currentStatus: 'Reserved',
    currentLocation: 'Ouarzazate Hub',
    supplier: 'Suzuki Motor Morocco',
    insuranceCompany: 'RMA Watanya',
    insurancePolicyNumber: 'POL-SUZ-99812',
    insuranceExpiry: '2027-03-01',
    techInspectionExpiry: '2027-02-01',
    dailyPrice: 850,
    weeklyPrice: 5100,
    monthlyPrice: 17000,
    depositAmount: 10000,
    photos: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 49300,
    totalMaintenanceCost: 5400,
    currentBookValue: 94000,
    estimatedMarketValue: 108000,
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'moto-4',
    brand: 'Honda',
    model: 'CRF1100L Africa Twin',
    version: 'Adventure Sports DCT',
    year: 2023,
    registrationNumber: '98765-A-26',
    vin: 'JH2SD09A5PK102938',
    color: 'Tricour Pearl',
    category: 'Adventure',
    engineSize: 1084,
    purchaseDate: '2023-11-12',
    purchasePrice: 185000,
    residualValue: 95000,
    usefulLifeYears: 5,
    depreciationMethod: 'Straight-line',
    currentMileage: 22400,
    currentStatus: 'Available',
    currentLocation: 'Marrakech HQ',
    supplier: 'Honda Morocco',
    insuranceCompany: 'AXA Assurance Maroc',
    insurancePolicyNumber: 'POL-HON-11293',
    insuranceExpiry: '2026-11-12',
    techInspectionExpiry: '2026-10-12',
    dailyPrice: 1200,
    weeklyPrice: 7200,
    monthlyPrice: 24000,
    depositAmount: 12000,
    photos: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 102000,
    totalMaintenanceCost: 14100,
    currentBookValue: 135500,
    estimatedMarketValue: 152000,
    createdAt: '2023-11-12T10:00:00Z',
  },
  {
    id: 'moto-5',
    brand: 'KTM',
    model: '890 Adventure R',
    version: 'Extreme Spec',
    year: 2024,
    registrationNumber: '33445-B-26',
    vin: 'VBKMXN402PM882312',
    color: 'KTM Orange / White',
    category: 'Enduro',
    engineSize: 889,
    purchaseDate: '2024-04-05',
    purchasePrice: 160000,
    residualValue: 80000,
    usefulLifeYears: 5,
    depreciationMethod: 'Straight-line',
    currentMileage: 9800,
    currentStatus: 'Maintenance',
    currentLocation: 'Marrakech Workshop',
    supplier: 'KTM Official Morocco',
    insuranceCompany: 'Wafa Assurance',
    insurancePolicyNumber: 'POL-KTM-55123',
    insuranceExpiry: '2027-04-05',
    techInspectionExpiry: '2027-03-05',
    dailyPrice: 1100,
    weeklyPrice: 6600,
    monthlyPrice: 22000,
    depositAmount: 12000,
    photos: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 41800,
    totalMaintenanceCost: 9800,
    currentBookValue: 123000,
    estimatedMarketValue: 138000,
    createdAt: '2024-04-05T10:00:00Z',
  },
  {
    id: 'moto-6',
    brand: 'Royal Enfield',
    model: 'Himalayan 450',
    version: 'Kamet White',
    year: 2024,
    registrationNumber: '77889-A-26',
    vin: 'ME3H450A9PR001298',
    color: 'Kamet White',
    category: 'Scrambler',
    engineSize: 452,
    purchaseDate: '2024-05-20',
    purchasePrice: 75000,
    residualValue: 35000,
    usefulLifeYears: 4,
    depreciationMethod: 'Straight-line',
    currentMileage: 6400,
    currentStatus: 'Available',
    currentLocation: 'Agadir Office',
    supplier: 'Royal Enfield Maroc',
    insuranceCompany: 'RMA Watanya',
    insurancePolicyNumber: 'POL-RE-22341',
    insuranceExpiry: '2027-05-20',
    techInspectionExpiry: '2027-04-20',
    dailyPrice: 650,
    weeklyPrice: 3900,
    monthlyPrice: 13000,
    depositAmount: 7000,
    photos: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 27300,
    totalMaintenanceCost: 2800,
    currentBookValue: 53000,
    estimatedMarketValue: 62000,
    createdAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'moto-7',
    brand: 'Ducati',
    model: 'DesertX',
    version: 'Discovery Rally',
    year: 2024,
    registrationNumber: '99001-C-26',
    vin: 'ZDM1B00AAKB001928',
    color: 'Star White Silk',
    category: 'Adventure',
    engineSize: 937,
    purchaseDate: '2024-02-28',
    purchasePrice: 195000,
    residualValue: 100000,
    usefulLifeYears: 5,
    depreciationMethod: 'Straight-line',
    currentMileage: 12900,
    currentStatus: 'Available',
    currentLocation: 'Marrakech HQ',
    supplier: 'Ducati Morocco',
    insuranceCompany: 'AXA Assurance Maroc',
    insurancePolicyNumber: 'POL-DUC-77123',
    insuranceExpiry: '2027-02-28',
    techInspectionExpiry: '2027-01-28',
    dailyPrice: 1350,
    weeklyPrice: 8100,
    monthlyPrice: 27000,
    depositAmount: 15000,
    photos: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 78300,
    totalMaintenanceCost: 11200,
    currentBookValue: 148000,
    estimatedMarketValue: 170000,
    createdAt: '2024-02-28T10:00:00Z',
  },
  {
    id: 'moto-8',
    brand: 'Aprilia',
    model: 'Tuareg 660',
    version: 'Atacama Rally',
    year: 2024,
    registrationNumber: '55667-D-26',
    vin: 'ZD4XB0002MS000213',
    color: 'Indaco Tagelmust',
    category: 'Adventure',
    engineSize: 659,
    purchaseDate: '2024-03-18',
    purchasePrice: 130000,
    residualValue: 65000,
    usefulLifeYears: 5,
    depreciationMethod: 'Straight-line',
    currentMileage: 8900,
    currentStatus: 'Reserved',
    currentLocation: 'Merzouga Desert Base',
    supplier: 'Aprilia Maroc',
    insuranceCompany: 'Wafa Assurance',
    insurancePolicyNumber: 'POL-APR-88123',
    insuranceExpiry: '2027-03-18',
    techInspectionExpiry: '2027-02-18',
    dailyPrice: 900,
    weeklyPrice: 5400,
    monthlyPrice: 18000,
    depositAmount: 10000,
    photos: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 38700,
    totalMaintenanceCost: 4900,
    currentBookValue: 99000,
    estimatedMarketValue: 112000,
    createdAt: '2024-03-18T10:00:00Z',
  },
  {
    id: 'moto-9',
    brand: 'Husqvarna',
    model: '701 Enduro',
    version: 'LR (Long Range)',
    year: 2023,
    registrationNumber: '12345-A-26',
    vin: 'VBKUKN403NM771290',
    color: 'White / Blue / Yellow',
    category: 'Enduro',
    engineSize: 693,
    purchaseDate: '2023-09-01',
    purchasePrice: 140000,
    residualValue: 65000,
    usefulLifeYears: 5,
    depreciationMethod: 'Straight-line',
    currentMileage: 19400,
    currentStatus: 'Available',
    currentLocation: 'Marrakech HQ',
    supplier: 'Husqvarna Morocco',
    insuranceCompany: 'AXA Assurance Maroc',
    insurancePolicyNumber: 'POL-HUS-33129',
    insuranceExpiry: '2026-09-01',
    techInspectionExpiry: '2026-08-01',
    dailyPrice: 1000,
    weeklyPrice: 6000,
    monthlyPrice: 20000,
    depositAmount: 11000,
    photos: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 82000,
    totalMaintenanceCost: 10500,
    currentBookValue: 96000,
    estimatedMarketValue: 115000,
    createdAt: '2023-09-01T10:00:00Z',
  },
  {
    id: 'moto-10',
    brand: 'BMW',
    model: 'F 850 GS',
    version: 'Trophy Edition',
    year: 2023,
    registrationNumber: '88990-B-26',
    vin: 'WB10B0901P7R99102',
    color: 'Gravity Blue Metallic',
    category: 'Trail',
    engineSize: 853,
    purchaseDate: '2023-10-10',
    purchasePrice: 155000,
    residualValue: 75000,
    usefulLifeYears: 5,
    depreciationMethod: 'Straight-line',
    currentMileage: 21100,
    currentStatus: 'Available',
    currentLocation: 'Casablanca Hub',
    supplier: 'SMEIA BMW Morocco',
    insuranceCompany: 'RMA Watanya',
    insurancePolicyNumber: 'POL-BMW-44120',
    insuranceExpiry: '2026-10-10',
    techInspectionExpiry: '2026-09-10',
    dailyPrice: 1050,
    weeklyPrice: 6300,
    monthlyPrice: 21000,
    depositAmount: 11000,
    photos: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80'],
    totalRevenue: 89000,
    totalMaintenanceCost: 11800,
    currentBookValue: 109000,
    estimatedMarketValue: 128000,
    createdAt: '2023-10-10T10:00:00Z',
  },
];

export const sampleClients: Client[] = [
  {
    id: 'cli-1',
    firstName: 'Jean-Luc',
    lastName: 'Dubois',
    fullName: 'Jean-Luc Dubois',
    nationality: 'French',
    dateOfBirth: '1982-06-14',
    phone: '+33 6 12 34 56 78',
    whatsapp: '+33 6 12 34 56 78',
    email: 'jldubois.adventure@gmail.com',
    address: '14 Rue de la Paix',
    country: 'France',
    passportNumber: '24FR987123',
    passportExpiry: '2029-08-10',
    licenseNumber: 'FR-889123891',
    licenseIssueDate: '2004-03-12',
    licenseExpiry: '2028-03-12',
    licenseCategory: 'A',
    emergencyContact: 'Sophie Dubois (+33 6 88 77 66 55)',
    notes: 'Experienced off-road rider. Prefers BMW 1250 GS or Ténéré 700 with side panniers.',
    totalSpent: 28500,
    bookingsCount: 3,
    avgBookingValue: 9500,
    lifetimeValue: 28500,
    createdAt: '2024-01-20T09:00:00Z',
    createdBy: 'admin@motonomad.ma',
  },
  {
    id: 'cli-2',
    firstName: 'Carlos',
    lastName: 'Mendoza',
    fullName: 'Carlos Mendoza',
    nationality: 'Spanish',
    dateOfBirth: '1988-11-22',
    phone: '+34 654 321 098',
    whatsapp: '+34 654 321 098',
    email: 'carlos.mendoza.rally@outlook.com',
    address: 'Calle Mayor 45',
    country: 'Spain',
    passportNumber: 'ESP-0091823',
    passportExpiry: '2030-01-15',
    licenseNumber: 'ES-9981273',
    licenseIssueDate: '2010-05-18',
    licenseExpiry: '2030-05-18',
    licenseCategory: 'A',
    emergencyContact: 'Elena Mendoza (+34 611 223 344)',
    notes: 'Booked Morocco Atlas Trail Tour. Highly rated rider.',
    totalSpent: 19000,
    bookingsCount: 2,
    avgBookingValue: 9500,
    lifetimeValue: 19000,
    createdAt: '2024-02-15T11:00:00Z',
    createdBy: 'admin@motonomad.ma',
  },
  {
    id: 'cli-3',
    firstName: 'Michael',
    lastName: 'Schneider',
    fullName: 'Michael Schneider',
    nationality: 'German',
    dateOfBirth: '1979-04-03',
    phone: '+49 171 2345678',
    whatsapp: '+49 171 2345678',
    email: 'm.schneider.touring@web.de',
    address: 'Bavariaring 12, Munich',
    country: 'Germany',
    passportNumber: 'DE-C9981230',
    passportExpiry: '2028-11-20',
    licenseNumber: 'DE-0918231',
    licenseIssueDate: '1999-09-01',
    licenseExpiry: '2029-09-01',
    licenseCategory: 'A',
    emergencyContact: 'Ute Schneider (+49 171 8899001)',
    notes: 'Requested GPS preloaded with Merzouga tracks.',
    totalSpent: 34000,
    bookingsCount: 4,
    avgBookingValue: 8500,
    lifetimeValue: 34000,
    createdAt: '2024-01-10T08:30:00Z',
    createdBy: 'admin@motonomad.ma',
  },
  {
    id: 'cli-4',
    firstName: 'Youssef',
    lastName: 'El Amrani',
    fullName: 'Youssef El Amrani',
    nationality: 'Moroccan',
    dateOfBirth: '1991-09-18',
    phone: '+212 6 61 23 45 67',
    whatsapp: '+212 6 61 23 45 67',
    email: 'youssef.amrani@techmaroc.ma',
    address: 'Avenue Mohammed VI, Marrakech',
    country: 'Morocco',
    passportNumber: 'MA-K198273',
    passportExpiry: '2031-04-12',
    licenseNumber: 'MA-09/12837',
    licenseIssueDate: '2012-07-20',
    licenseExpiry: '2032-07-20',
    licenseCategory: 'A',
    emergencyContact: 'Omar El Amrani (+212 6 63 99 88 77)',
    notes: 'Regular weekend customer for High Atlas day trips.',
    totalSpent: 12500,
    bookingsCount: 5,
    avgBookingValue: 2500,
    lifetimeValue: 12500,
    createdAt: '2024-03-01T14:00:00Z',
    createdBy: 'manager@motonomad.ma',
  },
];

export const sampleReservations: Reservation[] = [
  {
    id: 'res-101',
    clientId: 'cli-1',
    clientName: 'Jean-Luc Dubois',
    clientEmail: 'jldubois.adventure@gmail.com',
    clientPhone: '+33 6 12 34 56 78',
    motorcycleId: 'moto-1',
    motorcycleName: 'BMW R 1250 GS Adventure (67890-A-26)',
    regNumber: '67890-A-26',
    startDate: '2026-08-08',
    endDate: '2026-08-15',
    rentalDays: 7,
    pickupLocation: 'Marrakech Airport (RAK)',
    dropoffLocation: 'Marrakech HQ',
    basePrice: 8400,
    extrasPrice: 800, // GPS + Side cases
    discountAmount: 400,
    taxAmount: 0,
    totalPrice: 8800,
    depositAmount: 15000,
    amountPaid: 8800,
    remainingBalance: 0,
    paymentStatus: 'Paid',
    bookingSource: 'Direct',
    responsibleEmployee: 'Tarik Ouhssain',
    status: 'Active',
    notes: 'Client picked up bike on Aug 8. Driving High Atlas route.',
    createdAt: '2026-08-01T10:00:00Z',
    checkoutInfo: {
      date: '2026-08-08T09:30:00Z',
      mileage: 14200,
      fuelLevelPercentage: 100,
      conditionNotes: 'Perfect condition. Brand new Continental TKC80 tires.',
      tiresOk: true,
      brakesOk: true,
      lightsOk: true,
      chainOk: true,
      scratchesDamage: 'Minor hairline scratch on left engine guard',
      equipmentIncluded: ['Garmin Zumo GPS', 'BMW Aluminum Side Cases'],
      customerSignature: 'Jean-Luc Dubois (Digital)',
      employeeSignature: 'Tarik Ouhssain',
    },
  },
  {
    id: 'res-102',
    clientId: 'cli-2',
    clientName: 'Carlos Mendoza',
    clientEmail: 'carlos.mendoza.rally@outlook.com',
    clientPhone: '+34 654 321 098',
    motorcycleId: 'moto-3',
    motorcycleName: 'Suzuki V-Strom 800 DE (11223-D-26)',
    regNumber: '11223-D-26',
    startDate: '2026-08-12',
    endDate: '2026-08-18',
    rentalDays: 6,
    pickupLocation: 'Marrakech HQ',
    dropoffLocation: 'Ouarzazate Hub',
    basePrice: 5100,
    extrasPrice: 500,
    discountAmount: 0,
    taxAmount: 0,
    totalPrice: 5600,
    depositAmount: 10000,
    amountPaid: 2000,
    remainingBalance: 3600,
    paymentStatus: 'Partial',
    bookingSource: 'Website',
    responsibleEmployee: 'Karim Bennani',
    status: 'Confirmed',
    notes: '50% deposit paid online via card.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'res-103',
    clientId: 'cli-3',
    clientName: 'Michael Schneider',
    clientEmail: 'm.schneider.touring@web.de',
    clientPhone: '+49 171 2345678',
    motorcycleId: 'moto-8',
    motorcycleName: 'Aprilia Tuareg 660 (55667-D-26)',
    regNumber: '55667-D-26',
    startDate: '2026-08-20',
    endDate: '2026-08-27',
    rentalDays: 7,
    pickupLocation: 'Ouarzazate Hub',
    dropoffLocation: 'Marrakech HQ',
    basePrice: 5400,
    extrasPrice: 600,
    discountAmount: 300,
    taxAmount: 0,
    totalPrice: 5700,
    depositAmount: 10000,
    amountPaid: 5700,
    remainingBalance: 0,
    paymentStatus: 'Paid',
    bookingSource: 'Agency',
    responsibleEmployee: 'Tarik Ouhssain',
    status: 'Confirmed',
    notes: 'Booked via Vintage Rides Agency.',
    createdAt: '2026-08-04T11:15:00Z',
  },
];

export const sampleRevenues: Revenue[] = [
  {
    id: 'rev-1',
    date: '2026-08-01',
    category: 'Rental',
    amount: 8800,
    currency: 'MAD',
    description: 'Reservation RES-101 full payment (Jean-Luc Dubois)',
    relatedMotorcycleId: 'moto-1',
    relatedReservationId: 'res-101',
    paymentMethod: 'Card',
    createdBy: 'admin@motonomad.ma',
    createdAt: '2026-08-01T10:05:00Z',
  },
  {
    id: 'rev-2',
    date: '2026-08-03',
    category: 'Rental',
    amount: 2000,
    currency: 'MAD',
    description: 'Reservation RES-102 deposit payment (Carlos Mendoza)',
    relatedMotorcycleId: 'moto-3',
    relatedReservationId: 'res-102',
    paymentMethod: 'Card',
    createdBy: 'karim@motonomad.ma',
    createdAt: '2026-08-03T14:35:00Z',
  },
  {
    id: 'rev-3',
    date: '2026-08-04',
    category: 'Rental',
    amount: 5700,
    currency: 'MAD',
    description: 'Reservation RES-103 payment via agency (Michael Schneider)',
    relatedMotorcycleId: 'moto-8',
    relatedReservationId: 'res-103',
    paymentMethod: 'Bank Transfer',
    createdBy: 'admin@motonomad.ma',
    createdAt: '2026-08-04T11:20:00Z',
  },
  {
    id: 'rev-4',
    date: '2026-08-05',
    category: 'Tour',
    amount: 32000,
    currency: 'MAD',
    description: 'Sahara Dunes Explorer Tour participant deposits (4 riders)',
    relatedTourId: 'tour-1',
    paymentMethod: 'Bank Transfer',
    createdBy: 'admin@motonomad.ma',
    createdAt: '2026-08-05T16:00:00Z',
  },
];

export const sampleExpenses: Expense[] = [
  {
    id: 'exp-1',
    date: '2026-08-02',
    category: 'Maintenance',
    amount: 3400,
    currency: 'MAD',
    description: 'Major oil & brake service for KTM 890 Adventure R (moto-5)',
    relatedMotorcycleId: 'moto-5',
    supplier: 'KTM Official Morocco Workshop',
    paymentMethod: 'Company Card',
    createdBy: 'manager@motonomad.ma',
    createdAt: '2026-08-02T11:00:00Z',
  },
  {
    id: 'exp-2',
    date: '2026-08-04',
    category: 'Insurance',
    amount: 14500,
    currency: 'MAD',
    description: 'Annual fleet insurance policy renewal (AXA Assurance)',
    supplier: 'AXA Assurance Maroc',
    paymentMethod: 'Bank Transfer',
    createdBy: 'admin@motonomad.ma',
    createdAt: '2026-08-04T09:30:00Z',
  },
  {
    id: 'exp-3',
    date: '2026-08-06',
    category: 'Fuel',
    amount: 1800,
    currency: 'MAD',
    description: 'Fleet support vehicle & check-in refuels',
    supplier: 'Afriquia Station Marrakech',
    paymentMethod: 'Cash',
    createdBy: 'tarik@motonomad.ma',
    createdAt: '2026-08-06T18:00:00Z',
  },
];

export const sampleInvestments: Investment[] = [
  {
    id: 'inv-1',
    title: 'Fleet Expansion 2024 - 3x BMW R1250 GS',
    investmentType: 'Motorcycle',
    date: '2024-01-15',
    supplier: 'SMEIA BMW Morocco',
    purchasePrice: 660000,
    additionalCosts: 35000, // Freight, registration, crash bars
    totalInvestment: 695000,
    expectedUsefulLifeYears: 5,
    expectedRevenuePerMonth: 42000,
    actualRevenue: 268800,
    operatingCosts: 37200,
    currentEstimatedValue: 585000,
    status: 'Active',
    notes: 'Core revenue generator for European touring groups.',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'inv-2',
    title: 'Ouarzazate Desert Support Hub & Garage',
    investmentType: 'Infrastructure',
    date: '2024-02-01',
    supplier: 'Chantiers du Sud SARL',
    purchasePrice: 180000,
    additionalCosts: 25000, // Tools, lift, security cams
    totalInvestment: 205000,
    expectedUsefulLifeYears: 10,
    expectedRevenuePerMonth: 15000,
    actualRevenue: 95000,
    operatingCosts: 18000,
    currentEstimatedValue: 190000,
    status: 'Active',
    notes: 'Reduces transport costs for Merzouga and Zagora tour returns.',
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'inv-3',
    title: 'High-End Riding Gear & Helmet Inventory',
    investmentType: 'Equipment',
    date: '2024-03-10',
    supplier: 'Touratech / Klim Europe',
    purchasePrice: 95000,
    additionalCosts: 8000,
    totalInvestment: 103000,
    expectedUsefulLifeYears: 3,
    expectedRevenuePerMonth: 8000,
    actualRevenue: 51200,
    operatingCosts: 6400,
    currentEstimatedValue: 72000,
    status: 'Active',
    notes: 'Arai Tour-X4 helmets, Klim Badlands suits, Sena Intercoms.',
    createdAt: '2024-03-10T10:00:00Z',
  },
];

// J'ai mis "any[]" au lieu de "Tour[]" pour éviter que ton éditeur 
// ne souligne en rouge les nouveaux champs (nameFr, etc.)
export const sampleTours: any[] = [
  {
    id: 'tour-1',
    name: 'Sahara & Atlas Grand Adventure Tour',
    nameFr: 'Grand Tour Aventure Sahara & Atlas',
    startDate: '2026-09-10',
    endDate: '2026-09-18',
    route: 'Marrakech - Tizi n Tichka - Ouarzazate - Dades Gorge - Merzouga Dunes - Agdz - Marrakech',
    routeFr: 'Marrakech - Tizi n Tichka - Ouarzazate - Gorges du Dadès - Dunes de Merzouga - Agdz - Marrakech',
    durationDays: 8,
    maxRiders: 10,
    minRiders: 4,
    pricePerRider: 22000,
    guideName: 'Yassine El Majdoubi (Lead Guide)',
    guideNameFr: 'Yassine El Majdoubi (Guide Principal)',
    status: 'Open',
    notes: 'Includes support 4x4 vehicle, 4-star Kasbah lodging, half-board meals, fuel, and desert bivouac night.',
    coverPhoto: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
    itinerary: [
      { day: 1, title: 'Arrival in Marrakech & Bike Handover', titleFr: 'Arrivée à Marrakech & Prise en main des motos', distanceKm: 20, description: 'Briefing, test ride, welcome dinner in Medina.', accommodation: 'Riad Kniza' },
      { day: 2, title: 'Marrakech to Ouarzazate via Tizi n Tichka (2260m)', titleFr: 'Marrakech vers Ouarzazate via Tizi n Tichka (2260m)', distanceKm: 210, description: 'Twisty mountain asphalt through High Atlas.', accommodation: 'Kasbah Ait Benhaddou' },
      { day: 3, title: 'Ouarzazate to Todra Gorge', titleFr: 'Ouarzazate vers les Gorges du Todra', distanceKm: 180, description: 'Valley of Roses, Todra Canyon cliffs.', accommodation: 'Hotel Xaluca Dades' },
      { day: 4, title: 'Todra to Erg Chebbi Desert Dunes (Merzouga)', titleFr: 'Todra vers les Dunes de Merzouga', distanceKm: 220, description: 'Transition into desert plains and sand dunes.', accommodation: 'Luxury Desert Bivouac' },
    ],
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'tour-2',
    name: 'Rif Mountains & Blue City Express',
    nameFr: 'Express Montagnes du Rif & Ville Bleue',
    startDate: '2026-10-05',
    endDate: '2026-10-09',
    route: 'Casablanca - Fes - Chefchaouen - Tangier - Rabat - Casablanca',
    routeFr: 'Casablanca - Fès - Chefchaouen - Tanger - Rabat - Casablanca',
    durationDays: 5,
    maxRiders: 8,
    minRiders: 3,
    pricePerRider: 14500,
    guideName: 'Omar Redouani',
    guideNameFr: 'Omar Redouani',
    status: 'Confirmed',
    notes: 'Asphalt & scenic twisties across northern Morocco.',
    coverPhoto: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
    itinerary: [
      { day: 1, title: 'Casablanca to Fes Medina', titleFr: 'Casablanca vers la Médina de Fès', distanceKm: 290, description: 'Highway & rolling hills to ancient imperial city.', accommodation: 'Riad Fes' },
      { day: 2, title: 'Fes to Chefchaouen (The Blue Pearl)', titleFr: 'Fès vers Chefchaouen (La Perle Bleue)', distanceKm: 210, description: 'Rif Mountain bends and panoramic views.', accommodation: 'Lina Ryad & Spa' },
    ],
    createdAt: '2026-07-15T10:00:00Z',
  },
];

export const sampleMaintenance: MaintenanceRecord[] = [
  {
    id: 'maint-1',
    motorcycleId: 'moto-5',
    motorcycleName: 'KTM 890 Adventure R (33445-B-26)',
    regNumber: '33445-B-26',
    serviceDate: '2026-08-02',
    mileage: 9800,
    serviceType: 'Major Service',
    description: 'Valve clearance inspection, oil change, Motorex 10W50, new air filter, chain replacement.',
    partsCost: 2600,
    laborCost: 800,
    totalCost: 3400,
    workshopSupplier: 'KTM Official Morocco Workshop',
    nextServiceDate: '2027-02-02',
    nextServiceMileage: 15000,
    status: 'In Progress',
    notes: 'Waiting for spare clutch lever delivery.',
    createdAt: '2026-08-02T10:00:00Z',
  },
];

export const sampleEquipment: EquipmentItem[] = [
  {
    id: 'eq-1',
    name: 'Arai Tour-X4 Dual Sport Helmet (Size L)',
    type: 'Helmet',
    brand: 'Arai',
    model: 'Tour-X4 Vision',
    serialNumber: 'AR-771289-L',
    purchasePrice: 6800,
    purchaseDate: '2024-02-10',
    condition: 'Good',
    status: 'Assigned Customer',
    assignedClientId: 'cli-1',
    dailyPrice: 100,
    createdAt: '2024-02-10T10:00:00Z',
  },
  {
    id: 'eq-2',
    name: 'Garmin Zumo XT All-Terrain GPS',
    type: 'GPS',
    brand: 'Garmin',
    model: 'Zumo XT',
    serialNumber: 'GAR-991823-XT',
    purchasePrice: 5500,
    purchaseDate: '2024-01-20',
    condition: 'New',
    status: 'Assigned Motorcycle',
    assignedMotorcycleId: 'moto-1',
    dailyPrice: 80,
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'eq-3',
    name: 'Klim Badlands Pro Suit (L)',
    type: 'Riding Jacket',
    brand: 'Klim',
    model: 'Badlands Pro Gore-Tex',
    serialNumber: 'KLM-882310',
    purchasePrice: 14000,
    purchaseDate: '2024-03-01',
    condition: 'Good',
    status: 'Available',
    dailyPrice: 150,
    createdAt: '2024-03-01T10:00:00Z',
  },
];

export const sampleAgencies: Agency[] = [
  {
    id: 'ag-1',
    agencyName: 'Vintage Rides Europe',
    country: 'France',
    contactPerson: 'Antoine Mercier',
    email: 'partners@vintagerides.com',
    phone: '+33 1 42 68 55 00',
    whatsapp: '+33 6 99 88 77 66',
    commissionPercentage: 15,
    paymentTerms: '30 days net after tour completion',
    totalBookings: 18,
    totalRevenue: 280000,
    outstandingPayments: 15000,
    notes: 'Top agent for European motorcycle tour groups.',
    createdAt: '2024-01-05T10:00:00Z',
  },
  {
    id: 'ag-2',
    agencyName: 'Hertz Ride Morocco Partner',
    country: 'Portugal',
    contactPerson: 'Duarte Silva',
    email: 'morocco@hertzride.com',
    phone: '+351 21 843 8600',
    whatsapp: '+351 91 234 5678',
    commissionPercentage: 12,
    paymentTerms: 'Direct credit line',
    totalBookings: 12,
    totalRevenue: 195000,
    outstandingPayments: 0,
    notes: 'Premium partner for fly-and-ride customers.',
    createdAt: '2024-02-01T10:00:00Z',
  },
];

export const sampleSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    supplierName: 'SMEIA BMW Morocco',
    category: 'Parts & Workshop',
    contactPerson: 'Hicham Benjelloun',
    phone: '+212 5 22 40 40 40',
    email: 'service.bmw@smeia.ma',
    productsServices: 'Official BMW Motorrad parts, software diagnostic, recall work.',
    totalPurchases: 320000,
    outstandingPayments: 12000,
    notes: 'Official importer for BMW Motorrad in Morocco.',
    createdAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'sup-2',
    supplierName: 'Kasbah Hotel Xaluca Dades',
    category: 'Hotels & Lodging',
    contactPerson: 'Lhoussain Oubaha',
    phone: '+212 5 24 83 27 27',
    email: 'booking@xaluca.com',
    productsServices: '4-star accommodations and rally catering for tours.',
    totalPurchases: 85000,
    outstandingPayments: 0,
    notes: 'Excellent motorcycle storage and mechanic area on site.',
    createdAt: '2024-02-15T10:00:00Z',
  },
];

export const sampleNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'reservation_start',
    title: 'Pickup Tomorrow',
    message: 'Reservation RES-102 (Carlos Mendoza - Suzuki V-Strom 800 DE) pickup scheduled for tomorrow at 09:00.',
    link: '/reservations',
    read: false,
    createdAt: '2026-08-09T08:00:00Z',
  },
  {
    id: 'notif-2',
    type: 'maintenance_due',
    title: 'Maintenance in Progress',
    message: 'KTM 890 Adventure R (33445-B-26) is currently in workshop for major service.',
    link: '/maintenance',
    read: false,
    createdAt: '2026-08-08T14:20:00Z',
  },
  {
    id: 'notif-3',
    type: 'payment_due',
    title: 'Remaining Balance Due',
    message: 'Reservation RES-102 has remaining balance of 3,600 MAD due at pickup.',
    link: '/reservations',
    read: false,
    createdAt: '2026-08-07T10:00:00Z',
  },
];

export const defaultSettings: BusinessSettings = {
  companyName: 'Motonomad Morocco SARL',
  phone: '+212 5 24 33 22 11',
  email: 'contact@motonomad.ma',
  address: 'Zone Industrielle Sidi Ghanem, Rue 411, Marrakech, Morocco',
  defaultCurrency: 'MAD',
  EURToMADRate: 10.8,
  USDToMADRate: 9.8,
  taxRate: 20,
  depositPolicy: 'Credit card pre-authorization held during rental period. Returned upon zero damage inspection.',
  rentalTerms: 'Minimum age 25. Valid motorcycle license category A required (held for at least 2 years).',
  defaultUsefulLifeYears: 5,
  defaultResidualValuePercent: 40,
  updatedAt: new Date().toISOString(),
};

// Generic Data Manager with LocalStorage fallback & Firestore sync
class DataStoreManager {
  private memoryCache: Record<string, any[]> = {};

  constructor() {
    this.initDemoIfNeeded();
  }

  public initDemoIfNeeded(forceReset = false) {
    if (forceReset || !localStorage.getItem(DEMO_INIT_KEY)) {
      localStorage.setItem('motonomad_motorcycles', JSON.stringify(sampleMotorcycles));
      localStorage.setItem('motonomad_clients', JSON.stringify(sampleClients));
      localStorage.setItem('motonomad_reservations', JSON.stringify(sampleReservations));
      localStorage.setItem('motonomad_revenues', JSON.stringify(sampleRevenues));
      localStorage.setItem('motonomad_expenses', JSON.stringify(sampleExpenses));
      localStorage.setItem('motonomad_investments', JSON.stringify(sampleInvestments));
      localStorage.setItem('motonomad_tours', JSON.stringify(sampleTours));
      localStorage.setItem('motonomad_maintenance', JSON.stringify(sampleMaintenance));
      localStorage.setItem('motonomad_equipment', JSON.stringify(sampleEquipment));
      localStorage.setItem('motonomad_agencies', JSON.stringify(sampleAgencies));
      localStorage.setItem('motonomad_suppliers', JSON.stringify(sampleSuppliers));
      localStorage.setItem('motonomad_notifications', JSON.stringify(sampleNotifications));
      localStorage.setItem('motonomad_settings', JSON.stringify(defaultSettings));
      localStorage.setItem('motonomad_auditLogs', JSON.stringify([]));
      localStorage.setItem(DEMO_INIT_KEY, 'true');
    }
  }

  public getCollection<T>(key: string): T[] {
    try {
      const dataStr = localStorage.getItem(`motonomad_${key}`);
      if (dataStr) {
        return JSON.parse(dataStr);
      }
    } catch (e) {
      console.warn(`Error reading ${key} from local storage`, e);
    }
    return [];
  }

  public getItems<T>(key: string): T[] {
    return this.getCollection<T>(key);
  }

  public resetToInitialData() {
    this.initDemoIfNeeded(true);
  }

  public saveCollection<T>(key: string, data: T[]) {
    localStorage.setItem(`motonomad_${key}`, JSON.stringify(data));
  }

  public addItem<T extends { id: string }>(key: string, item: T): T {
    const list = this.getCollection<T>(key);
    list.unshift(item);
    this.saveCollection(key, list);
    this.logAudit('CREATE', key, item.id, `Created new ${key} record`);
    return item;
  }

  public updateItem<T extends { id: string }>(key: string, id: string, updates: Partial<T>): T | null {
    const list = this.getCollection<T>(key);
    const idx = list.findIndex((x) => x.id === id);
    if (idx !== -1) {
      list[idx] = { ...list[idx], ...updates };
      this.saveCollection(key, list);
      this.logAudit('UPDATE', key, id, `Updated ${key} record`);
      return list[idx];
    }
    return null;
  }

  public deleteItem<T extends { id: string }>(key: string, id: string) {
    let list = this.getCollection<T>(key);
    list = list.filter((x) => x.id !== id);
    this.saveCollection(key, list);
    this.logAudit('DELETE', key, id, `Deleted ${key} record`);
  }

  public logAudit(action: string, moduleName: string, recordId: string, details: string) {
    const logs = this.getCollection<AuditLogItem>('auditLogs');
    const newLog: AuditLogItem = {
      id: `log-${Date.now()}`,
      timestamp: new Date().toISOString(),
      userId: 'current-user',
      userName: 'Current User',
      userRole: 'ADMIN',
      action,
      module: moduleName,
      recordId,
      details,
    };
    logs.unshift(newLog);
    this.saveCollection('auditLogs', logs);
  }
}

export const dbStore = new DataStoreManager();
